### ISSUE TITLE
Support Structure View for XQuery modules

### ISSUE THREAD

**Issue by willsthompson** [rhdunn/xquery-intellij-plugin#100]
Structure view is especially useful for large library modules. It's already implemented nicely in https://github.com/ligasgr/intellij-xquery, but that plugin seems to choke on large modules.

**Comment by rhdunn** [comment]
I have now implemented support for this, which will be in the 1.5 release.

I have also tested it on several large files -- the MarkLogic xdmp built-in functions, which has a large number of functions, and the XQueryML30.xq XQuery parser file, which is 30613 lines of XQuery code. Both of these responded near instantaneously on my local testing.
