### ISSUE TITLE
Provide a way of viewing and navigating REST APIs

### ISSUE THREAD

**Issue by rhdunn** [rhdunn/xquery-intellij-plugin#129]
### EXQuery RESTXQ

Several XQuery vendors support the exquery restxq module that allows users to define REST endpoints that call specific XQuery functions.

The relevant XQuery modules should be scanned for rest annotations and displayed in IntelliJ using the specified `%rest:path`.

### rewriter.xml

MarkLogic supports a `rewriter.xml` file for this, that maps incoming REST queries to XQuery main modules, allowing parameters to be passed to those queries. The queries can then forward these onto specific functions, which is harder to map to specific functions or indirectly called modules.

### MarkLogic Roxy

The roxy library supports two types of mappings:
1.  *views*, that map to another XQuery main module that is used to display a view/page.
2.  *controllers*, that map to functions within a given module.

It should be possible to support these in such a way that it can be possible to list all the available REST calls and map those to controller methods, or main module views. This should be generic and configurable, with defaults provided for the roxy mapping logic.

**Comment by cfoster** [comment]
Hi Reece,

Just in case you were not aware, MarkLogic supports RESTXQ too via XQRS.

https://consulting.xmllondon.com/xqrs

**Comment by cfoster** [comment]
Also,

If you want, I can make a very simple HTTP API for your IntelliJ plugin to generate RESTXQ Stubs from OpenAPI/Swagger interface files

https://consulting.xmllondon.com/openapi-marklogic

Just let me know, it'll only take me 5 minutes to setup for you.

**Comment by rhdunn** [comment]
@cfoster I was aware of your XQRS project.

The HTTP API to the RESTXQ stub generator looks interesting. I'm not sure when I will get to implementing this functionality, or making use of that API, as I have other things to work on. Thanks for the suggestion, though. It may be useful for other projects/IDEs as well.

**Comment by rhdunn** [comment]
This has now been implemented for RESTXQ and rewriter XML files by implementing the IntelliJ Ultimate Endpoint Provider API so they appear in the Endpoints tool window.
