### ISSUE TITLE
The plugin is not compatible with IntelliJ IDEA 2020.2.1

### ISSUE THREAD

**Issue by lcahlander** [rhdunn/xquery-intellij-plugin#140]
Is there an update coming?

**Comment by CanOfBees** [comment]
Hi @lcahlander - I'm using version 1.7.2-202 on IDEA 2020.2.1 Build #IU-202.6948.69. I want to say that IDEA got confused about the package and I needed to disable/re-enable (or something) to get the plugin to update, but it's been several days.

**Comment by rhdunn** [comment]
Hmm. The plugin should be compatible with 2020.2.1. What error are you getting?

**Comment by rhdunn** [comment]
If you've recently upgraded to a new major version of IntelliJ (e.g. 2020.1 -> 2020.2), IntelliJ may not have updated the plugin, so you will need to check manually.

Which version of the plugin do you have? I'm wondering if IntelliJ is ignoring the part after the '-' so thinks you are on the latest version of the plugin. I was told that doing that would work (allowing me to upload the same version of the plugin targetting different versions of IntelliJ), but maybe this is a case where it doesn't work properly.

**Comment by dizzzz** [comment]
as there is no response :-(

<img width="420" alt="image" src="https://user-images.githubusercontent.com/1700062/94599172-5afcdf80-0290-11eb-8b90-b85f398753bc.png">

**Comment by rhdunn** [comment]
@dizzzz Thanks for the screenshot.

The version you have (1.7-201) is specifically built for IntelliJ 2020.1, as the IntelliJ APIs change between major versions -- it targets that major version only, so that is why it is saying that the version you have is incompatible. Looking at https://plugins.jetbrains.com/plugin/8612-xquery-intellij-plugin/versions/stable/91598, there is a 1.7-202 and 1.7.2-202 version available.

Is IntelliJ saying that there is an update available? If not, I can ask a question on the IntelliJ forum.

**Comment by dizzzz** [comment]
Thnx for your fast response!

I do not see that an update is available, assuming I need to check here: 
<img width="374" alt="image" src="https://user-images.githubusercontent.com/1700062/94608200-52f76c80-029d-11eb-8bb2-9a7060a0d217.png">

Forcing detecting plugin updates do not yield into such indication.

**Comment by rhdunn** [comment]
Thanks. I'm not sure why that is happening. I've created a post on the IntelliJ forums (https://intellij-support.jetbrains.com/hc/en-us/community/posts/360009784600-Upgrading-from-2020-1-to-2020-2-is-saying-my-plugin-is-incompatible-not-offering-an-update-) to see if it is something I need to be doing, or is an IntelliJ bug when checking for upgrades/compatibility.

If you want to update the plugin without that fix/resolution, you would likely need to uninstall the 201 version of my plugin (by clicking on the down arrow next to the disable button), then install my plugin again -- it should detect version 1.7.2-202 (the current version for IntelliJ 2020.2). The uninstall shouldn't require a restart as the plugin shouldn't be loaded given that it was detected to be incompatible.

**Comment by rhdunn** [comment]
I've created a new 1.8.0 release which will address the versioning if I release a minor 1.8.1 update and a user has also updated their IntelliJ version, so this particular issue should not happen again.
