### ISSUE TITLE
EXPath Crypto module question

### ISSUE THREAD

**Issue by CanOfBees** [rhdunn/xquery-intellij-plugin#141]
Hi Reece - 

Apologies for the slow movement on getting you some updates. I'm working through the current BaseX modules and would appreciate some advice regarding updates to the EXPath crypto functions.

I see now that you have the following in `src/plugin-expath/main/resources/org/expath/ns/crypto.xqy`:
```xquery
declare %a:restrict-since("$key", "expath-crypto", "1.0-20110810", "xs:string")
        %a:restrict-until("$key", "basex", "8.6", "xs:string")
        %a:restrict-since("$key", "basex", "8.6", "(xs:string|xs:hexBinary|xs:base64Binary)")
        %a:since("expath-crypto", "1.0-20110810") function crypto:hmac($message as xs:string, $key as xs:anyAtomicType, $algorithm as xs:string) as xs:base64Binary external;
```
The changes to the BaseX implementation in version 9.3 updates the type for `$message` from `xs:string` to `xs:anyAtomicType`. My initial thought was that having an additional `%a:restrict-since()` annotation would work, but... I'm not sure! Can the `restrict-since` annotation occur more than once if the arguments are different?

Here is what I started to work up:
```xquery
declare %a:restrict-since("$key", "expath-crypto", "1.0-20110810", "xs:string")
        %a:restrict-until("$key", "basex", "8.6", "xs:string")
        %a:restrict-since("$key", "basex", "8.6", "(xs:string|xs:hexBinary|xs:base64Binary)")
        %a:restrict-since("$message", "basex", "9.3", "xs:anyAtomicType")
        %a:since("expath-crypto", "1.0-20110810") function crypto:hmac($message as xs:string, $key as xs:anyAtomicType, $algorithm as xs:string) as xs:base64Binary external;
```
Does that look right? 

Thanks for any guidance and advice you're willing to share.

**Comment by CanOfBees** [comment]
I found some other examples and now I realize that the signature should look something like this:
```xquery
declare %a:restrict-since("$key", "expath-crypto", "1.0-20110810", "xs:string")
        %a:restrict-until("$key", "basex", "8.6", "xs:string")
        %a:restrict-since("$key", "basex", "8.6", "(xs:string|xs:hexBinary|xs:base64Binary)")
        %a:restrict-until("$message", "basex", "9.3", "xs:string")
        %a:restrict-since("$message", "basex", "9.3", "xs:anyAtomicType")
        %a:since("expath-crypto", "1.0-20110810") function crypto:hmac($message as xs:string, $key as xs:anyAtomicType, $algorithm as xs:string) as xs:base64Binary external;
```
Let me know if I'm still missing the mark here. Thanks for your help!

**Comment by rhdunn** [comment]
That should work. The intention is to have them being specific to the parameter, so the type on the function itself is the generalized version, and the restrict annotations define the specific type matching the criteria. Also note that I haven't yet added checking for this annotation.
