### ISSUE TITLE
fn:doc() call incorrectly flags as error 

### ISSUE THREAD

**Issue by markschiffner** [rhdunn/xquery-intellij-plugin#143]
Plugin signature documentation on fn:doc is $uri  as  xs:string?)  as  document-node()?
MarkLogic signature for fn:doc is fn:doc(
   [$uri as xs:string*]
) as document-node()*

This causes the plugin to produce error: XPST0017: The number of arguments do not match a function.
Since it is very common to use cts:search(fn:doc(), $query) in marklogic, it would be greatly appreciated to not indicate this as an error.

**Comment by rhdunn** [comment]
I've added support for this in the current 1.9.0 development release. That version will be released when the IntelliJ 2021.1 release is stable (typically once the RC build is released).
