### ISSUE TITLE
The plugin is not compatible with IntelliJ IDEA 2022.2

### ISSUE THREAD

**Issue by thomaszbz** [rhdunn/xquery-intellij-plugin#158]
As of IntelliJ IDEA 2022.2 (IU-222.3345.118), the plugin "XQuery and XSLT" version 1.9.3-221 is disabled and IntelliJ says "Incompatible: requires IDE build 221.* or earlier".

For me, the new version of IntelliJ got installed via snap, the IntelliJ built stems from July 26, 2022. That said, 2022.2 is available now.

As far as I can see, some progress has already been made via https://github.com/rhdunn/xquery-intellij-plugin/commit/677a74ccc3e73120b83be2c07d35e8f36f144832 

However, a release is still outstanding.

**Comment by rhdunn** [comment]
I've released a build for IntelliJ 2020.2. It was delayed because I was on holiday last week.
