### ISSUE TITLE
Not compatible with IntelliJ IDEA 2023.3

### ISSUE THREAD

**Issue by jhellingman** [rhdunn/xquery-intellij-plugin#163]
After upgrading to IntelliJ IDEA 2023.3, it tells me this plug-in is no longer compatible.

Details:

IntelliJ IDEA 2023.3 (Ultimate Edition)
Build #IU-233.11799.241, built on December 2, 2023

**Comment by mardukbp** [comment]
@rhdunn It would be great if you could find the time to release a new version :)

**Comment by mnuman** [comment]
@rhdunn Same here, it was an unpleasant surprise when I found out that your plugin wasn't working anymore after upgrading IntelliJ to 2023.3 :-(

**Comment by aerisnju** [comment]
Hi @jhellingman @mardukbp @mnuman 
You could try my build before @rhdunn updates the official one.
https://github.com/aerisnju/xquery-intellij-plugin/releases/download/build-for-233/xquery-intellij-plugin-1.10.0-233-snapshot.zip

**Comment by jhellingman** [comment]
Things appear to work again (using IntelliJ IDEA 2023.3 (Ultimate Edition) Build #IU-233.11799.241, built on December 2, 2023)

Thanks.

**Comment by mnuman** [comment]
Well done @aerisnju, suggest you create a PR for your changes to be incorporated into the "official" distribution! Thanks.

**Comment by rhdunn** [comment]
Apologies for the delay. I've been busy with other projects and things. A 2023.3 compatible build should now be available.

**Comment by mardukbp** [comment]
No worries. Thanks a lot!
