### ISSUE TITLE
Plugin not compatible with IntelliJ IDEA 2024.1

### ISSUE THREAD

**Issue by BBaumgartnerSF** [rhdunn/xquery-intellij-plugin#165]
After upgrading to IntelliJ IDEA 2024.1 the plug-in is no longer compatible.

IDE Details:
IntelliJ IDEA 2024.1 (Ultimate Edition)
Build #IU-241.14494.240, built on March 28, 2024

Would be great if you could release a new, compatible version. Thanks!

**Comment by BBaumgartnerSF** [comment]
**Workaround:** 
Downloaded the plugin from here and installed it manually:
https://github.com/rhdunn/xquery-intellij-plugin/actions/runs/8101954588
=> xquery-intellij-plugin-LATEST-EAP-SNAPSHOT works for IntelliJ IDEA 2024.1 👍

**Comment by neilsf** [comment]
For those, like me, who attempted to install the plugin manually and got an error. Unzip the downloaded file first. There will be another zip file inside. That is what you need.
