### ISSUE TITLE
Latest plugin (1.9.4-233) not compatible with PhpStorm 2024.1

### ISSUE THREAD

**Issue by kemal-xx** [rhdunn/xquery-intellij-plugin#166]
It was compatible with PhpStorm 2023.3.6

I just noticed that issue #165 is the same as mine, except the title is (according to me) not correct

**Comment by jacekszymanski** [comment]
FWIW, I built the plugin from [here](https://github.com/aerisnju/xquery-intellij-plugin/tree/fix-build-233) with `IDEA_VERSION='2024.1' gradle build -x test` and it seems to work. But I'm using mostly for XQuery.
