### ISSUE TITLE
Built-in Function Documentation

### ISSUE THREAD

**Issue by rhdunn** [rhdunn/xquery-intellij-plugin#42]
- [ ] W3C Functions and Objects 1.0 (First Edition)
- [ ] W3C Functions and Objects 1.0 (Second Edition)
- [ ] W3C Functions and Objects 3.0
- [ ] W3C Functions and Objects 3.1
- [ ] MarkLogic 6.0
- [ ] MarkLogic 7.0
- [ ] MarkLogic 8.0
- [ ] Saxonica 9.7

**Comment by CanOfBees** [comment]
@rhdunn - hi and happy 2019 to you. I'd like to give a bit more help if you're willing to accept it. 

Regarding this issue: my initial thought is to have the static functions [documented in the appropriate `builtin` directories](https://github.com/rhdunn/xquery-intellij-plugin/tree/master/src/main/resources/builtin). Is that inline with your requirements for this, or do you see the xqdoc somewhere else?

I suppose that brings up another question - is xqdoc appropriate, or did you have a different approach in mind?

Thanks for your time!
Best

**Comment by rhdunn** [comment]
Hi, Happy 2019! Help is always appreciated.

That's correct. My idea regarding this issue is to extend the built-in XQuery files to add the documentation to the function declarations, etc. -- that is one of the motivations for defining the built-ins in XQuery. Ideally, this should be in xqDoc.

And yes, the built-in documentation should support all built-in functions from the various vendors and specifications.

The idea is to include the following elements:
1. summary as the first paragraph in the xqDoc documentation
2. rules as the following paragraph(s)
3. notes as the paragraphs after that
4. errors expressed using the xqdoc annotations
5. see xqdoc annotations linking to the primary documentation for the function/etc. (BaseX wiki, W3C specification, etc.)

NOTE: The parameter and return documentation should be contained in the rules paragraphs like is done in the W3C and BaseX documentation.

I'm not currently sure how to handle functions with default arguments (i.e. where there are two or more definitions for the same function name). For now, just document the function with the most parameters and when I have a solution to the issue, I'll update as needed.

**Comment by CanOfBees** [comment]
Hi @rhdunn - apologies for I've had a slow start on this. When you have a few minutes, I'd like to get a bit of feedback [on initial work](https://github.com/CanOfBees/xquery-intellij-plugin/blob/42-built-in-functions-w3c-1.0v1-xqdocs/src/main/resources/builtin/www.w3.org/2005/xpath-functions.xqy#L21-L94), particularly the following:

* I've generally been letting text wrap for summaries, rules, and notes, but wanted to verify that was acceptable. I know some stylistic decisions suggest much shorter lines (~80 columns or so), but since this documentation is meant to be processed by IDEA and your plugin I wasn't sure. [Shorter lines](https://github.com/CanOfBees/xquery-intellij-plugin/blob/42-built-in-functions-w3c-1.0v1-xqdocs/src/main/resources/builtin/www.w3.org/2005/xpath-functions.xqy#L65-L66) vs [wrapped lines](https://github.com/CanOfBees/xquery-intellij-plugin/blob/42-built-in-functions-w3c-1.0v1-xqdocs/src/main/resources/builtin/www.w3.org/2005/xpath-functions.xqy#L70). Thoughts here?
* I've been keeping a blank line between the summary and each rule/note. Does that matter? If the xqDoc parsing process doesn't need the whitespace, then I'll happily pull them out. 
* I started to add zero-or-one for `?`, zero-one-or-more for `*`, and one-or-more for `+` in the parameters.... Any thoughts about this? I currently have a mix - I wasn't sure which approach is more appropriate. Let me know and I'll make things consistent.

Again, sorry for the slow start. Thanks for your help.

**Comment by rhdunn** [comment]
Hi, no problem.

Wrapping lines is fine. For the main Kotlin source code, I am using the default 120 columns. For the built-in functions, I haven't currently been wrapping the definintions, preferring to keep them on one line. For the documentation, 80 or 100 columns should be used consistently if you want to wrap the lines.

Keeping the blank lines is the correct approach -- the documentation processor should interpret these as new paragraphs, and separate the summary (first line/paragraph) from the rest.

The documentation processor will infer the type of the parameters and return values. Because the parameters and return value are documented in the rules, these are not needed and should be removed. Compare http://docs.basex.org/wiki/Map_Module#map:contains with http://exist-db.org/exist/apps/fundocs/view.html?uri=http://www.w3.org/2005/xpath-functions/map&location=java:org.exist.xquery.functions.map.MapModule. NOTE: My preference is for the W3C/EXPath specification style you are currently using.

The errors should be of the form `error-id description`, e.g.
```
@error err:FOCA0002 if $paramQName does not have the correct lexical form for an instance of xs:QName.
```

**Comment by CanOfBees** [comment]
> The documentation processor will infer the type of the parameters and return values. Because the parameters and return value are documented in the rules, these are not needed and should be removed. Compare http://docs.basex.org/wiki/Map_Module#map:contains with http://exist-db.org/exist/apps/fundocs/view.html?uri=http://www.w3.org/2005/xpath-functions/map&location=java:org.exist.xquery.functions.map.MapModule. NOTE: My preference is for the W3C/EXPath specification style you are currently using.
> 
> The errors should be of the form `error-id description`, e.g.
> 
> ```
> @error err:FOCA0002 if $paramQName does not have the correct lexical form for an instance of xs:QName.
> ```

Just to make sure, then continuing with the following is okay?
```
(:~
 : Summary
 : 
 : Note/Rule
 :
 : Note/Rule
 :
 : \@param $arg as xs:string?.
 : \@param $arg as xs:string?.
 : \@return xs:QName.
 : \@see http://example.com
 :)
```
Apologies - it seems like determining style for these is a bit more difficult than some other languages' doc blocks. 

Thanks for your feedback!

**Comment by rhdunn** [comment]
Example:
```
(:~
 : Returns an xs:QName value formed using a supplied namespace URI and lexical QName.
 :
 : The namespace URI in the returned QName is taken from $paramURI. If $paramURI is the zero-length string or the empty sequence, it represents "no namespace".
 :
 : The prefix (or absence of a prefix) in $paramQName is retained in the returned xs:QName value.
 :
 : The local name in the result is taken from the loacl part of $paramQName.
 :
 : @error A dynamic error is raised [err:FOCA0002] if $paramQName does not have the correct lexical form for an instance of xs:QName.
 : @error A dynamic error is raised [err:FOCA0002] if $paramURI is the zero-length string or the empty sequence, and the value of $paramQName contains a colon ( : ).
 : @error A dynamic error may be raised [err:FOCA0002] if $paramURI is not a valid URI (XML Namespaces 1.0) or IRI (XML Namespaces 1.1).
 :
 : @see https://www.w3.org/TR/xpath-functions/#func-QName
 : @see https://www.w3.org/TR/xpath-functions/#ERRFOCA0002
 :)
declare %a:since("xpath-functions", "1.0-20070123") function fn:QName($paramURI as xs:string?, $paramQName as xs:string) as xs:QName external;
```

1. I was mistaken about the format of the `@error` field, so using the specification format/wording is fine.
1. Line wrapping in the above is taken from the version you had. Consistency is the main thing I am interested in. Wrapping at 100 columns may make it easier to read/edit, but that is mainly for development of the plugin. Users will be viewing it via the IntelliJ documentation UI once I implement the documentation integration APIs that IntelliJ provides for that.
1. I've added a separator between the `@error` and `@see` fields. That is not necessary, but might make it easier to differentiate the two groups. I'll let you decide what to do for this.

**Comment by CanOfBees** [comment]
That's super helpful - thank you! The lack of params... it looks weird to me, but in this context I'm happy to follow this. I'll add that separator between `\@error` and `@see`, too.

**Comment by rhdunn** [comment]
I've now implemented support for this by downloading and reading the W3C specifications, and am extending the support for other documentation sources.
