### ISSUE TITLE
Find usages not working at all or not working properly

### ISSUE THREAD

**Issue by ligasgr** [rhdunn/xquery-intellij-plugin#46]
https://github.com/rhdunn/xquery-intellij-plugin/issues/30 mentions support for finding usages.
For a simple scenario like:
```xquery
let $x := ''
return $x
```
navigation to declaration place works fine but finding usage on $x in first line doesn't do anything.
Same for:
```xquery
declare variable $x := '';
$x
```

For scenario with function like below:
```xquery
declare default function namespace 'http://www.w3.org/2005/xquery-local-functions';
declare function x() {'a'};
x()
```
Find usages on function declaration gives results for completely unrelated usages of *global and local variables* with name $x.

**Comment by rhdunn** [comment]
This was caused by various issues in the references and resolution logic, and possibly other factors. The cases listed above are now working correctly.
