### ISSUE TITLE
Built-in Functions: BaseX

### ISSUE THREAD

**Issue by rhdunn** [rhdunn/xquery-intellij-plugin#54]
### Namespaces (http://docs.basex.org/wiki/Module_Library)
- [x] admin: http://docs.basex.org/wiki/Admin_Module
- [x] archive: http://docs.basex.org/wiki/Archive_Module
- [x] bin: http://docs.basex.org/wiki/Binary_Module [expath]
- [x] client: http://docs.basex.org/wiki/Client_Module
- [x] convert: http://docs.basex.org/wiki/Conversion_Module
- [x] crypto: http://docs.basex.org/wiki/Cryptographic_Module [expath]
- [x] csv: http://docs.basex.org/wiki/CSV_Module
- [x] db: http://docs.basex.org/wiki/Database_Module
- [x] fetch: http://docs.basex.org/wiki/Fetch_Module
- [x] file: http://docs.basex.org/wiki/File_Module [expath]
- [x] ft: http://docs.basex.org/wiki/Full-Text_Module
- [x] hash: http://docs.basex.org/wiki/Hashing_Module
- [x] hof: http://docs.basex.org/wiki/Higher-Order_Functions_Module
- [x] html: http://docs.basex.org/wiki/HTML_Module
- [x] http: http://docs.basex.org/wiki/HTTP_Module [expath]
- [x] index: http://docs.basex.org/wiki/Index_Module
- [x] inspection: http://docs.basex.org/wiki/Inspection_Module
- [x] jobs: http://docs.basex.org/wiki/Jobs_Module
- [x] json: http://docs.basex.org/wiki/JSON_Module
- [x] out: http://docs.basex.org/wiki/Output_Module
- [x] proc: http://docs.basex.org/wiki/Process_Module
- [x] prof: http://docs.basex.org/wiki/Profiling_Module
- [x] random: http://docs.basex.org/wiki/Random_Module
- [x] repo: http://docs.basex.org/wiki/Repository_Module
- [x] sql: http://docs.basex.org/wiki/SQL_Module
- [x] stream: http://docs.basex.org/wiki/Streaming_Module
- [x] strings: http://docs.basex.org/wiki/Strings_Module
- [x] unit: http://docs.basex.org/wiki/Unit_Module
- [x] user: http://docs.basex.org/wiki/User_Module
- [x] util: http://docs.basex.org/wiki/Utility_Module
- [x] validate: http://docs.basex.org/wiki/Validation_Module
- [x] web: http://docs.basex.org/wiki/Web_Module
- [x] xquery: http://docs.basex.org/wiki/XQuery_Module
- [x] xslt: http://docs.basex.org/wiki/XSLT_Module
- [x] zip: http://docs.basex.org/wiki/ZIP_Module [expath]

**Comment by CanOfBees** [comment]
@rhdunn hello (and thanks again for the pointers). This looks like an issue I can help with, but I have a question: how do you prefer to address changes in BaseX modules across BaseX versions; e.g. changes in the admin module from v8.0 to v8.3 to v9.0[1]. 

Are you wanting these variations approached similarly to how the [MarkLogic XDMP dbg.xqy](https://github.com/rhdunn/xquery-intellij-plugin/blob/master/src/main/resources/builtin/marklogic.com/xdmp/dbg.xqy#L11-L12) is written? Use the `%a:since` annotation and check for versions?

Cheers!

[1] [BaseX Admin Module changelog](http://docs.basex.org/wiki/Admin_Module#Changelog)

**Comment by rhdunn** [comment]
Yes, that's the general idea. There are other annotations as well (see https://github.com/rhdunn/xquery-intellij-plugin/blob/master/src/main/resources/builtin/reecedunn.co.uk/xquery/annotations.xqy). For example, https://github.com/rhdunn/xquery-intellij-plugin/blob/master/src/main/resources/builtin/marklogic.com/cts.xqy. The idea is to support these in the plugin, but that is not implemented yet.

The module files should be in a path matching the namespace. e.g. `/builtin/basex.org/modules/archive.xqy`. This allows the plugin to locate the functions from a namespace declaration only.

If the function has a different type signature across versions, I have been using things like `cts:box-north($box as cts:box) (: as [5.0]xs:float [9.0]xs:numeric :)`. Similarly for generalised union values (e.g. `$options (: as [5.0]element() [8.0](element()|map:map)? :)`). I'm not sure how to properly deal with these.

**Comment by CanOfBees** [comment]
A follow-up question: would you prefer a "bulk" PR; e.g. all modules as single PR, or would you prefer each module as separate PR?

**Comment by rhdunn** [comment]
Whichever works best for you. For the MarkLogic modules, I added them all at once for version 5.0, then updated by version (6.0, 7.0, ...). Adding them a module at a time is fine. I prefer self-contained commits, but for things like this I don't mind how they are organised.

**Comment by CanOfBees** [comment]
I'm planning to make the remainder of the modules a single PR. I'm sorry for the wave of small PRs - I hope you don't mind. The next one will take a bit but should get the rest in one.

Cheers!

**Comment by CanOfBees** [comment]
@rhdunn - another question, apologies. It looks like some of the argument names have changed, at least according to the wiki; e.g. [older version of `csv:parse`](http://docs.basex.org/index.php?title=CSV_Module&oldid=13642#csv:parse) vs [newer version of same](http://docs.basex.org/wiki/CSV_Module#csv:parse) -- i.e.:
```xquery
(: older version(s) :)
csv:parse($input as xs:string)
(: new version :)
csv:parse($string as xs:string?)
```
.Does it make any sense to indicate this in the declaration? I've indicated the type change[1], but I'm not sure if the argument name change matters. I'm inclined to think that it doesn't but wanted to check.

[1] [CSV Module](https://github.com/CanOfBees/xquery-intellij-plugin/blob/54-BaseX-builtin-functions/src/main/resources/builtin/basex/modules/csv.xqy)

**Comment by rhdunn** [comment]
I would personally use the newer argument name. However, either are fine.

Re: versions. I would go by the changelog in the documentation unless that is not accurate. If you are not sure on an exact version, a major/minor version should be fine.

**Comment by CanOfBees** [comment]
Thanks for the feedback. 

Do you envision articulating *all* versions of a implementation, or is there a reasonable cutoff for older versions? I.e. go back to BaseX v1.0, or BaseX v7.8?

**Comment by rhdunn** [comment]
Ideally, the versions should match when the function was added/modified/removed to provide accurate information in the IDE.

Realistically, recording only the version information from the changelog should be sufficient (only going through the version history to look up the signature of deleted functions mentioned in the changelog).

__NOTE:__ This includes going back as far as v1.0 where relevant.

**Comment by rhdunn** [comment]
Hi, I have some feedback for your ongoing work on this issue:
1.  The `array` module is already supported as it is a W3C function module -- see `builtin/www.w3.org/2005/xpath-functions/array.xqy`. You don't need to add a version for BaseX. __NOTE:__ The same applies to other W3C function namespaces.
1.  It would be helpful to not commit invalid XQuery (e.g. in 7fcce309108d8223ea2f14b81cb84e5a34152c01) -- you can use `git commit --amend` to update an existing commit if you are saving incomplete work between edits.
1.  Some of the modules (e.g. crypto.xqy) have the IntelliJ template comment.
1.  Don't set the baseline version for since annotations if the function is not introduced then (e.g. for db.xqy).
1.  The file location should match the namespace URI (e.g. crypto.xqy should be in `builtin/expath.org/ns`).

__NOTE:__ The other BaseX modules should be in `builtin/basex.org/modules` (note the `.org` in `basex.org`!)

**Comment by CanOfBees** [comment]
Hi, I wonder if you could expand on the following:
> Ideally, the versions should match when the function was added/modified/removed to provide accurate information in the IDE.
> 
> Realistically, recording only the version information from the changelog should be sufficient (only going through the version history to look up the signature of deleted functions mentioned in the changelog).
> 
> **NOTE:** This includes going back as far as v1.0 where relevant.

I think I have a better understanding of what you're wanting to accomplish here, but I have some concerns, specifically in regards to the BaseX database module. Based on historical changelog info from the wiki, the [earliest entry for the db module is Dec. 2010](http://docs.basex.org/index.php?title=Database_Module&oldid=87), but there isn't any [specific ChangeLog info until Feb. 2012](http://docs.basex.org/index.php?title=Database_Module&direction=next&oldid=5474) which only articulates changes for [versions 7.0 and 7.1](http://docs.basex.org/index.php?title=Database_Module&direction=next&oldid=5474#Recent_Changes).

> ```
> 4. Don't set the baseline version for since annotations if the function is not introduced then (e.g. for db.xqy).
> ```

I'm positive I've got some bad data in here so I'm not trying to excuse my sloppiness, but this general problem was making me think treating v7.8 as a baseline would be acceptable; i.e. there would be some equivalency with the Extensions introduced in v7.8. However, as I mentioned, I'm seeing this differently now. 

Unfortunately, I'm not sure how to handle/approach the lack of accurate change info prior to Feb. 2012/v7.(0|1). Would setting v7.0 as a baseline for the `since` annotation meet your approval? 

Thanks!

**Comment by rhdunn** [comment]
This is what I meant by ideally vs realistically. For example, the MarkLogic version information only goes back to version `5.0`.

As such, I am happy for `7.0` to be the oldest version in the since annotations.
