### ISSUE TITLE
Built-in Functions: Saxon

### ISSUE THREAD

**Issue by rhdunn** [rhdunn/xquery-intellij-plugin#56]
### Versions
- [x] Saxonica 9.7
- [x] Saxonica 9.8
### Namespaces
- [x] saxon: http://www.saxonica.com/html/documentation/functions/saxon/

**Comment by CanOfBees** [comment]
Hi @rhdunn - if you're okay with some additional contributions, may I start work on this issue?

**Comment by rhdunn** [comment]
Sure, go ahead. Thanks for your work adding the BaseX built-in functions.

**Comment by CanOfBees** [comment]
Apologies for I've been slow to get a start on this issue. 

I have a couple of questions regarding structure and syntax in the `.xqy` files.
1. I've added a `saxon.sf.net` directory; (see [this branch](https://github.com/CanOfBees/xquery-intellij-plugin/tree/56-Saxon-builtin-functions/src/main/resources/builtin)), but after starting reading through the Saxon function signatures I'm unsure if I should be approaching this like
```
builtin/saxon.sf.net/static-context/
builtin/saxon.sf.net/saxon/saxon.xqy
```
or 
```
builtin/saxon.sf.net/static-context/
builtin/saxon.sf.net/saxon/adjust-to-civil-time.xqy
builtin/saxon.sf.net/saxon/array-member.xqy
...
```
i.e. I started in with the first approach but didn't get very far before I thought the second approach was the correct one. I need some help :).
2. I think that the `o:requires` declaration is a more natural fit with each signature as a separate file, but I'm unsure. 

Any thoughts or suggestions would be very helpful. As always, thanks very much for your time and trouble.

Cheers!

**Comment by rhdunn** [comment]
All of those functions are declared in the same namespace, so should be in the same file. I would suggest to use `builtin/saxon.sf.net/default.xqy` -- I need to add support for that in my plugin, so function resolution will not currently work for that file.

The module namespace should be:

    module namespace saxon = "http://saxon.sf.net/";

I don't think `o:requires` is relevant here (it is mainly for the shared expath/exquery modules.

For the PE/EE restriction, I would use something like:

    declare %a:since("saxon/pe", "9.2") %a:since("saxon/ee", "9.2") function ...

I have seen the `jt:` namespace elsewhere in the Saxonica documentation, but cannot remember where. I think it is `http://saxon.sf.net/java-type` (http://www.saxonica.com/html/documentation/extensibility/functions/). You could try running something like `<jt:test/>` to check.

**Comment by CanOfBees** [comment]
I've finished adding function signatures for 9.7, 9.8 (and 9.9 signatures as well). I'm almost ready to PR this, but I have one question: the [saxon:pedigree](http://www.saxonica.com/html/documentation/functions/saxon/pedigree.html) returns something that I wasn't sure how to articulate; i.e. from the documentation: "tuple(container: function(*), key: anyAtomicType?, index: xs:integer?)?".

My understanding is pretty rough, and I wasn't sure how to articulate that. [I committed some syntactically bad XQuery](https://github.com/CanOfBees/xquery-intellij-plugin/blob/56-Saxon-builtin-functions/src/main/resources/builtin/saxon.sf.net/default.xqy#L64) (apologies!), but will happily change it, once I have a clear idea of what that return type is supposed to look like.

Is it meant to be a `map(*)` or `array(*)`? 
Thanks for your help!

**Comment by rhdunn** [comment]
That is a Saxon syntax extension (http://www.saxonica.com/html/documentation/extensions/syntax-extensions/tuple-types.html) and is meant to be as is (including the key names). It defines the key names and associated types of a map. I have support for that syntax extension in my plugin.

**Comment by CanOfBees** [comment]
Well, thank you - I had missed the Saxon syntax extension documentation.

Looking closer now, I see that I've included the Saxon 9.9 function signatures ( I really need to stop working on this while my kid is getting to sleep ). I'll be happy discard them if you want them excluded.

Lastly, there are a few XSLT-only functions - I left these out; however I'm happy to add them in if you want them in the list for completeness.

Thanks!

**Comment by CanOfBees** [comment]
Thanks for the feedback!

**Comment by rhdunn** [comment]
Thanks for adding support for this.
