### ISSUE TITLE
Built-in Functions: eXist-db

### ISSUE THREAD

**Issue by rhdunn** [rhdunn/xquery-intellij-plugin#90]
References:
1. http://exist-db.org/exist/apps/fundocs/browse.html?w3c=true&extensions=true&appmodules=true

**Comment by rhdunn** [comment]
Hi,

Regarding point 1, the structure in `builtin/` follows the structure of the namespaces (i.e. mapping `http://some-namespace-path` to `builtin/some-namespace-path.xqy`). If the eXist-db namespaces follow the structure you mention, then that is the correct structure.

Regarding point 2, don't worry about getting the version information correct for the functions if that information is not easily available.

Thanks for your work adding the built-in function definitions.

**Comment by CanOfBees** [comment]
Hi. I'm making some slow progress on these, and I have a question/concern: it looks like there are a number of duplicated namespaces; e.g.
the `demo` namespace at [`exist-db.org/apps/demo`](https://github.com/CanOfBees/xquery-intellij-plugin/blob/3332b65251ee8a581469560ec0e6ac2ec0a1283f/src/main/resources/builtin/exist-db.org/apps/demo.xqy#L8) and [`exist-db.org/apps/restxq/demo`](https://github.com/CanOfBees/xquery-intellij-plugin/blob/3332b65251ee8a581469560ec0e6ac2ec0a1283f/src/main/resources/builtin/exist-db.org/apps/restxq/demo.xqy#L8); see also the exist-db [static-context/xquery.xqy](https://github.com/CanOfBees/xquery-intellij-plugin/blob/3332b65251ee8a581469560ec0e6ac2ec0a1283f/src/main/resources/builtin/exist-db.org/static-context/xquery.xqy#L25-L47).

I'll continue to work through these, but I'm not certain how to handle these. Your thoughts, suggestions, and/or input would be greatly appreciated.

Thanks!

**Comment by CanOfBees** [comment]
I tried to think about this, but I'm not sure this is valid or appropriate in the context of your plugin. For situations like this (and they only seem to occur here in eXist -- maybe there are similar issues in Zorba, Galax, or XQuantum? Seems unlikely, but I don't know), could these be expressed as: 

``` xquery
import module namespace demo = "http://exist-db.org/apps/demo"
                                                                 at "http://exist-db.org/apps/demo.xqy", 
                                                                      "http://exist-db.org/apps/demo/restxq/demo.xqy";
```
I know that's not really syntactically valid in the context of the plugin. Maybe an annotation would be appropriate for this? 

Apologies if this is just extra noise. Thanks!

**Comment by rhdunn** [comment]
From my testing, it looks like from the http://exist-db.org/exist/apps/fundocs/browse.html?extensions=true list, namespaces where the location starts with `/db/` are not included in the static context, but those where the location starts with `java:` are. Note that `/db/` is the base path for files in the eXist-db database, and as such don't need to be listed by this plugin.

-----

You can test if a namespace is pre-declared in the static context by using something like:

    <fn:test/>

In this example, it is testing if `fn` (the XQuery function namespace) is in the static context. This returns:

    <fn:test xmlns:fn="http://www.w3.org/2005/xpath-functions"/>

Using `<demo:test/>`, I get:

    err:XPTY0004 'demo:test' is not a valid element name [at line 1, column 2, source: <demo:test/>]

This indicates that `demo` is not part of the static context.

**Comment by CanOfBees** [comment]
Thanks for the feedback and help! I've made some changes to get my work inline with your observations; additionally, I'll also be sure to check/verify the namespaces.

**Comment by CanOfBees** [comment]
@rhdunn - hi. I think that I'm almost ready to submit a PR for this issue, but I have a lingering question, that may warrant some additional feedback from the eXist community: it looks as though the functions in [eXist's Math module](http://exist-db.org/exist/apps/fundocs/view.html?uri=http://exist-db.org/xquery/math&location=java:org.exist.xquery.modules.math.MathModule) are deprecated (moved to w3's xpath function namespaces), broken (e.g. degrees() and radians(), or replicate w3 functions (e.g. ceil -> fn:ceiling()).

I wouldn't have a problem trying to articulate the deprecated/replicated function signatures, but I'm missing a namespace for the module; e.g. in eXide, `<math:test/>` evaluates to `<math:test xmlns:math="http://www.w3.org/2005/xpath-functions/math"/>. How would you like me to handle this? 

Thanks!

**Comment by rhdunn** [comment]
The linked documentation for eXist's Math module specifies `http://exist-db.org/xquery/math` as the namespace in which the functions are declared. Using:

    <a xmlns="http://exist-db.org/xquery/math"/>

returns:

    <math-ext:a xmlns:math-ext="http://exist-db.org/xquery/math"/>

As such, the static context should have:

    declare namespace math-ext = "http://exist-db.org/xquery/math";

How are degrees/radians broken? With:

    math-ext:degrees(1)

I get:

    5.729577951308232e1

NOTE: `degrees` and other eXist math extension functions are not visible in the `math` module, which is the W3C XPath and XQuery math function namespace.

**Comment by CanOfBees** [comment]
Thanks for helping with that - I was confused by the lack of an obvious namespace on the documentation, and then I didn't think enough about how to test the static context. 
Apologies!

**Comment by rhdunn** [comment]
No problem. Thanks again for working on this.
